wait_service() needs to handle wireless/remote device(s).
Bug: 290267160

Test: For these tests, use the hotspot network (which will allow wireless
adb). Alternatively, a non-corp wireless network (with less stringent
security config) would also work out (tested with both these setups).

aosp-osx/aosp-master-with-phones$adb kill-server
aosp-osx/aosp-master-with-phones$adb devices
List of devices attached
35081FDJG001TR	device

aosp-osx/aosp-master-with-phones$adb tcpip 5555
restarting in TCP mode port: 5555
aosp-osx/aosp-master-with-phones$adb shell ifconfig | grep 'inet'
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope: Host
          inet6 addr: fe80::a47b:7bff:fefc:62bc/64 Scope: Link
          inet addr:10.0.0.101  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: 2601:644:8e80:620:7fe:431:2c23:ecf3/64 Scope: Global
          inet6 addr: fe80::2040:22ff:feaa:8d09/64 Scope: Link
          inet6 addr: 2601:644:8e80:620:2040:22ff:feaa:8d09/64 Scope: Global
aosp-osx/aosp-master-with-phones$adb connect 10.0.0.101:5555
connected to 10.0.0.101:5555
aosp-osx/aosp-master-with-phones$adb devices
List of devices attached
35081FDJG001TR	device
10.0.0.101:5555	device

Test ambiguity:
aosp-osx/aosp-master-with-phones$adb  wait-for-disconnect
error: ambiguous: -s needs to be specified
Test disconnect of the wirelessly connected device - you can either
switch to 'Airplane Mode', disable Wifi on-device, or manually
disconnect from the network(on-device).
aosp-osx/aosp-master-with-phones$adb -s 10.0.0.101:5555  wait-for-disconnect
A noiceable delay is to be expected since the behavior of TCP/IP is to
expect polling (to detect disconnects).
Verify that the target device goes offline.
aosp-osx/aosp-master-with-phones$adb devices
List of devices attached
35081FDJG001TR	device
10.0.0.101:5555	offline

Test reconnect (when 'Airplane mode' is turned off, for e.g.):
aosp-osx/aosp-master-with-phones$adb devices
List of devices attached
35081FDJG001TR	device
10.0.0.101:5555	device

(Regression) Test wait-for-disconnect for the USB transport:
aosp-osx/aosp-master-with-phones$adb -s 35081FDJG001TR wait-for-disconnect
Disconnect USB device physically.
aosp-osx/aosp-master-with-phones$adb devices
List of devices attached
10.0.0.101:5555	device

Test wait-for-disconnect without a -s parameter:
Since there is only one (wirelessly connected) active transport, the -s param is not needed.
aosp-osx/aosp-master-with-phones$adb  wait-for-disconnect
aosp-osx/aosp-master-with-phones$adb devices
List of devices attached
10.0.0.101:5555	offline

Test reinstatement to kCsDevice (from offline) mode:
Turn wifi on (or 'Airplane mode' off) on-device.
aosp-osx/aosp-master-with-phones$adb devices
List of devices attached
10.0.0.101:5555	device

Test disconnect from a secondary terminal:
For this, run `adb disconnect 10.0.0.101:5555` from an other terminal
(make sure `adb wait-for-disconnect` below is launched first).
aosp-osx/aosp-master-with-phones$adb  wait-for-disconnect
aosp-osx/aosp-master-with-phones$adb devices
List of devices attached

Change-Id: I3c94dafb8a2a5769c73416e8a3eba45ce53959f0