adb: Fix compiler error due to SetThreadDescription name collision
This fixes name conflict with actual SetThreadDescription function declaration.
The compiler error is as following.

sysdeps_win32.cpp:3092:89: error: 'typedef HRESULT (* SetThreadDescription)(HANDLE, PCWSTR)'
redeclared as different kind of entity
processthreadsapi.h:358:29: note: previous declaration 'HRESULT SetThreadDescription(HANDLE, PCWSTR)'
sysdeps_win32.cpp: In function 'int adb_thread_setname(const std::string&)':
sysdeps_win32.cpp:3098:57: error: 'SetThreadDescription' does not name a type

Change-Id: If3563c7ad49d843808a221c02bbf7e0b2a1b5a19